services:
  postgres:
    image: pgduckdb/pgduckdb:17-main
    container_name: lab-postgres
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data
      # jalankan init SQL cuma saat volume baru (first boot)
      - ./db/init:/docker-entrypoint-initdb.d:ro

  metabase:
    image: metabase/metabase:latest
    container_name: lab-metabase
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${METABASE_PORT}:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - mbdata:/metabase-data

volumes:
  pgdata:
  mbdata:
