services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: lab-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: lab-metabase
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    ports:
      - "3000:3000"
    volumes:
      - mbdata:/metabase-data

volumes:
  pgdata:
  mbdata:
